# Generated by Django 3.0.3 on 2020-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200314_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
