# Generated by Django 3.0.3 on 2020-04-04 11:17

import core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_register_login_method"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", core.managers.CustomUserManager()),],
        ),
    ]
