# Generated by Django 3.0.3 on 2020-02-25 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('exercises', models.ManyToManyField(blank=True, related_name='listsCarousels', to='exercises.Exercise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listsCarousels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
