# Generated by Django 3.0.3 on 2020-02-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcarousel',
            name='user',
        ),
    ]
