# Generated by Django 3.0.3 on 2020-02-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0002_remove_listcarousel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=80)),
                ('file', models.ImageField(upload_to='category_photos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lists_carousels.ListCarousel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
