# Generated by Django 3.0.3 on 2020-02-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcarousel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
