# Generated by Django 3.0.3 on 2020-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0004_listcarousel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='listcarousel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
