# Generated by Django 3.0.3 on 2020-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20200225_0919'),
        ('lists_carousels', '0005_auto_20200225_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcarousel',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='listscarousels', to='exercises.Exercise'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(),
        ),
    ]
