# Generated by Django 3.0.3 on 2020-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0006_auto_20200225_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
