# Generated by Django 3.0.3 on 2020-02-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0007_photo_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='video_url',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('video_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=80)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lists_carousels.ListCarousel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
