# Generated by Django 3.0.3 on 2020-02-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0008_auto_20200225_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caption',
            new_name='image_caption',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='video_caption',
        ),
    ]
