# Generated by Django 3.0.3 on 2020-02-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0009_auto_20200225_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
