# Generated by Django 3.0.3 on 2020-03-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200324_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='exercises',
        ),
    ]
