# Generated by Django 3.0.3 on 2020-02-16 15:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
