# Generated by Django 3.0.3 on 2020-02-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200225_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='exercises.Exercise'),
        ),
    ]
