# Generated by Django 3.0.3 on 2020-02-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20200225_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
    ]
