# Generated by Django 3.0.3 on 2020-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_remove_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='summary',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
