# Generated by Django 3.0.3 on 2020-02-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20200225_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('video_caption', models.CharField(blank=True, max_length=80)),
                ('video_url', models.URLField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='exercises.Exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
