# Generated by Django 3.0.3 on 2020-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0010_delete_video'),
        ('exercises', '0012_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='Exercise', to='lists_carousels.ListCarousel'),
        ),
    ]
