# Generated by Django 3.0.3 on 2020-02-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_exercise_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='category',
            new_name='list_carousel',
        ),
    ]
