# Generated by Django 3.0.3 on 2020-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists_carousels', '0010_delete_video'),
        ('exercises', '0015_remove_exercise_list_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='list_carousel',
            field=models.ManyToManyField(blank=True, related_name='Exercise', to='lists_carousels.ListCarousel'),
        ),
    ]
