# Generated by Django 3.0.3 on 2020-03-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_exercise_list_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='list_carousel',
        ),
    ]
