# Generated by Django 3.0.3 on 2020-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_remove_exercise_list_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, upload_to='exercise_photos'),
        ),
    ]
